# 规格查询数据源
from agileone_interface.base.specification_operation import query_specification_count, get_current_specification_numbers, \
    add_specification

SPECIFICATION_QUERY_DATA = [
    [{'currentpage': '1'}, 'totalRecord'],
    [{'currentpage': '0'}, 'error'],
    [{'currentpage': '9000'}, 'error'],
    [{'currentpage': 1}, 'error'],
    [{'currentpage': ''}, 'error'],
    [{}, 'totalRecord'],
    [{"currentpage": 'asdfsad'}, 'error']
]
# 增加规格数据源
SPECIFICATION_ADD_DATA = [
    [{"userstoryid": "9",
      "type": "All-In-One",
      "content": "测试文本"}, get_current_specification_numbers],
    [{}, "error"],
    [{"userstoryid": "afdaa",
      "type": "All-In-One",
      "content": "fsdfsdf"}, "error"],
    [{"userstoryid": "",
      "type": "All-In-One",
      "content": "fsdfsdf"}, "error"],
    [{"type": "All-In-One",
      "content": "fsdfsdf"}, "error"],
    [{"userstoryid": "1000",
      "type": "All-In-One",
      "content": "fsdfsdf"}, "error"],
    [{"userstoryid": "1",
      "type": "foiwuoru",
      "content": "fsdfsdf"}, "error"],
    [{"userstoryid": "1",
      "type": "",
      "content": "fsdfsdf"}, "error"],
    [{"userstoryid": "1",
      "content": "fsdfsdf"}, "error"],
    [{"userstoryid": "1",
      "type": "1",
      " content": "fsdfsdf"}, "error"],
]

# 编辑规格数据
SPECIFICATION_EDIT_DATA = [
    [{"specid": "19",
      "userstoryid": "5",
      "type": "Requirement-Spec",
      "content": "fsdfsdf"}, "1"],
    [{}, "error"],
    [{"specid": "qwrw",
      "userstoryid": "5",
      "type": "Requirement-Spec",
      "content": "fsdfsdf"}, "error"],
    [{"specid": "",
      "userstoryid": "5",
      "type": "Requirement-Spec",
      "content": "fsdfsdf"}, "error"],
    [{"userstoryid": "5",
      "type": "Requirement-Spec",
      "content": "fsdfsdf"}, "error"],
    [{"specid": "10000",
      "userstoryid": "5",
      "type": "Requirement-Spec",
      "content": "fsdfsdf"}, "error"],
    [{"specid": "1",
      "userstoryid": "wertfwert",
      "type": "Requirement-Spec",
      "content": "fsdfsdf"}, "error"],
    [{"specid": "1",
      "userstoryid": "",
      "type": "Requirement-Spec",
      "content": "fsdfsdf"}, "error"],
    [{"specid": "1",
      "type": "Requirement-Spec",
      "content": "fsdfsdf"}, "error"],
    [{"specid": "1",
      "userstoryid": "1000000",
      "type": "Requirement-Spec",
      "content": "fsdfsdf"}, "error"],
    [{"specid": "1",
      "userstoryid": "5",
      "type": "fdafspec",
      "content": "fsdfsdf"}, "error"],
    [{"specid": "1",
      "userstoryid": "5",
      "type": "",
      "content": "fsdfsdf"}, "error"],
    [{"specid": "1",
      "userstoryid": "5",
      "content": "fsdfsdf"}, "error"],
    [{"specid": "1",
      "userstoryid": "5",
      "type": "11",
      "content": "fsdfsdf"}, "error"],
    [{"specid": "19",
      "userstoryid": "5",
      "type": "Requirement-Spec",
      "content": ""}, "1"],
    [{"specid": "19",
      "userstoryid": "5",
      "type": "Requirement-Spec"}, "1"],

]

# 删除规格数据
SPECIFICATION_DEL_DATA = [
    [{"specid": "19"},'1'],
    [{"specid": ""}, "error"],
    [{}, "error"],
    [{"specid": "asfwerw"}, "error"],
    [{"specid": "100000"}, "error"],

]
